name: Trigger Target Workflow

on:
  workflow_run:
    workflows: ["PROD Release on release push"]
    types:
      - completed  

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print event
        run: echo "${{ toJSON(github.event) }}"
      # - name: Trigger Workflow in Another Repository
      #   run: |
      #     # Set the required variables
      #     repo_owner="wandervik" 
      #     repo_name="github-actions-tut"  
      #     event_type="trigger-workflow" 
      #     curl -X POST \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       -H "Authorization: Bearer ${{ secrets.PAT }}" \
      #      https://api.github.com/repos/wandervik/github-actions-tut/actions/workflows/tests-ext.yml/dispatches \
      #       -d '{"ref":"master","inputs":{"pageos":"v1.0.0"}}'
