name: Deploy lambda

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        default: 'dev'

jobs:
  deploy-dev:
    name: Deploy lambda to dev

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
          path: 'package.json'
          prop_path: 'version'
    - run: echo "VERSION=${{steps.version.outputs.prop}}" >> $GITHUB_ENV

    - name: Put current version
      run: |
        python3 insert-version.py new_version ${{ env.VERSION }}


    - name: Deploy lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: eu-central-1
        function_name: version
        source: lambda-var.js

  deploy-prod:
    name: Deploy lambda to prod

    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
          path: 'package.json'
          prop_path: 'version'
    - run: echo "VERSION=${{steps.version.outputs.prop}}" >> $GITHUB_ENV

    - name: Put current version
      run: |
        python3 insert-version.py new_version ${{ env.VERSION }}


    - name: Deploy lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        function_name: version
        source: lambda-var.js

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1


    - name: Update Cloudfront
      run: |
        aws cloudfront get-distribution-config --id E3MY6RLJJ44XBK --output json > dist-cfg.json


    - name: Update version
      uses: jossef/action-set-json-field@v1
      with:
        file: dist-cfg.json
        # field: DistributionConfig.DefaultCacheBehavior.LambdaFunctionAssociations.Items.LambdaFunctionARN
        field: LambdaFunctionAssociations.Items.LambdaFunctionARN
        value: "arn:aws:lambda:us-east-1:519140963702:function:version:8"


    - name: Debug
      run: |
        cat dist-cfg.json

    # - name: Update distribution
    #   run: |
    #     aws cloudfront update-distribution --id E3MY6RLJJ44XBK --distribution-config dist-cfg.json