name: PR test

on:
  pull_request:


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2


    - run: echo "the action has been successfully summoned"