name: Release on tag push

on:
  push:
    tags:
    - 'ver/*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "deployin to path s3://test-path/${{ github.ref_name }}"