name: Release on tag push

on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: dev

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - run: echo "VERSION = ${{ github.ref_name/v/ }}" >> $GITHUB_ENV

      - name: Deploy
        run: echo "deployin to path s3://test-path/${{ env.VERSION }}"