name: Test workflow

on:
  push:
    branches: [ 'castiel' ]

jobs:
  test-job:

    name: Test job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - run: echo 'works'