name: Access token

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        default: "dev"

jobs:
  test:
    name: Test token

    runs-on: ubuntu-latest
    environment: dev

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: touch file
      run: touch ~/.netrc

    - name: Access token
      run: echo "machine github.com login ltarabarova password ${{ secrets.ACCESS_TOKEN }}" >> ~/.netrc

    - name: DEBUG OWBNER
      run: git ls-remote -h -t https://github.com/wandervik/test-token.git


    - name: DEBUG
      run: cat ~/.netrc
