name: Access token

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        default: "dev"

jobs:
  test:
    name: Test token

    runs-on: ubuntu-latest
    environment: dev

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: touch file
      run: touch ~/.netrc

    - name: Access token
<<<<<<< HEAD
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: echo "machine github.com login ltarabarova password ${{ env.ACCESS_TOKEN }}" >> ~/.netrc

    - name: DEBUG OWBNER
      run: |
        whoami
        cd ..
        ls -al
=======
      run: echo "machine github.com login ${{ secrets.ACCESS_TOKEN }}" >> ~/.netrc
>>>>>>> 51dcf3fb234f720fbc83ca0eddb1f8779b492377

    - name: DEBUG
      run: cat ~/.netrc
